-- Plugin compilation system for caching plugin configurations
local M = {}

-- Get the cache directory
local cache_dir = vim.fn.stdpath("cache") .. "/nvim-plugins"
local compiled_file = cache_dir .. "/plugins-compiled.lua"
local hash_file = cache_dir .. "/plugins-hash.txt"

-- Ensure cache directory exists
local function ensure_cache_dir()
    if vim.fn.isdirectory(cache_dir) == 0 then
        vim.fn.mkdir(cache_dir, "p")
    end
end

-- Generate hash of all plugin files
local function generate_hash()
    local plugins_dir = vim.fn.stdpath("config") .. "/lua/plugins"
    local plugin_files = vim.fn.globpath(plugins_dir, "*.lua", false, true)

    -- Sort for consistency
    table.sort(plugin_files)

    local hash_data = {}
    for _, file in ipairs(plugin_files) do
        -- Get file modification time and size as a simple hash
        local stat = vim.loop.fs_stat(file)
        if stat then
            local filename = vim.fn.fnamemodify(file, ":t")
            table.insert(hash_data, filename .. ":" .. stat.mtime.sec .. ":" .. stat.size)
        end
    end

    return table.concat(hash_data, "|")
end

-- Read stored hash
local function read_hash()
    if vim.fn.filereadable(hash_file) == 0 then
        return nil
    end

    local f = io.open(hash_file, "r")
    if not f then
        return nil
    end

    local hash = f:read("*all")
    f:close()
    return hash
end

-- Write hash to file
local function write_hash(hash)
    ensure_cache_dir()
    local f = io.open(hash_file, "w")
    if f then
        f:write(hash)
        f:close()
    end
end

local function extract_returned_function(content)
    local start_pattern = "return%s+function%s*%(%s*%)"
    local start_pos, return_end = content:find(start_pattern)
    if not start_pos then
        return nil
    end

    local body_start = return_end + 1
    if content:sub(body_start, body_start) == "\n" then
        body_start = body_start + 1
    end

    local end_start = content:match("()end%s*$")
    if not end_start then
        return nil
    end

    return {
        prelude = vim.trim(content:sub(1, start_pos - 1)),
        body = content:sub(body_start, end_start - 1),
    }
end

-- Compile all plugin files into a single file
function M.compile()
    local plugins_dir = vim.fn.stdpath("config") .. "/lua/plugins"
    local plugin_files = vim.fn.globpath(plugins_dir, "*.lua", false, true)

    -- Sort for consistency
    table.sort(plugin_files)

    local output = {
        "-- Auto-generated compiled plugins file",
        "-- DO NOT EDIT MANUALLY - This file is automatically generated",
        "",
        "local M = {}",
        "",
    }

    -- Generate plugin loading functions
    for _, file in ipairs(plugin_files) do
        local plugin_name = vim.fn.fnamemodify(file, ":t:r")

        -- Skip files starting with underscore
        if plugin_name:sub(1, 1) ~= "_" then
            table.insert(output, string.format('M["%s"] = function()', plugin_name))

            -- Read the plugin file content
            local f = io.open(file, "r")
            if f then
                local content = f:read("*all")
                f:close()

                -- Preserve any top-level helpers before `return function()`, then
                -- inline the returned function body into the compiled plugin.
                local returned_function = extract_returned_function(content)

                if returned_function then
                    if returned_function.prelude ~= "" then
                        table.insert(output, returned_function.prelude)
                        table.insert(output, "")
                    end
                    table.insert(output, returned_function.body)
                else
                    -- If pattern doesn't match, include the whole content wrapped
                    table.insert(output, "    return function()")
                    table.insert(output, "    " .. content)
                    table.insert(output, "    end")
                end
            end

            table.insert(output, "end")
            table.insert(output, "")
        end
    end

    table.insert(output, "return M")

    -- Write compiled file
    ensure_cache_dir()
    local f = io.open(compiled_file, "w")
    if f then
        f:write(table.concat(output, "\n"))
        f:close()

        -- Update hash
        local hash = generate_hash()
        write_hash(hash)

        return true
    end

    return false
end

-- Check if cache is valid
function M.is_cache_valid()
    -- Check if compiled file exists
    if vim.fn.filereadable(compiled_file) == 0 then
        return false
    end

    -- Check if hash matches
    local current_hash = generate_hash()
    local stored_hash = read_hash()

    return current_hash == stored_hash
end

-- Load compiled plugins
function M.load_compiled()
    if not M.is_cache_valid() then
        vim.notify("Plugin cache invalid, recompiling...", vim.log.levels.INFO)
        if not M.compile() then
            vim.notify("Failed to compile plugins", vim.log.levels.ERROR)
            return nil
        end
    end

    -- Load the compiled module
    local ok, compiled = pcall(dofile, compiled_file)
    if not ok then
        vim.notify("Failed to load compiled plugins: " .. tostring(compiled), vim.log.levels.ERROR)
        return nil
    end

    return compiled
end

-- Force recompilation
function M.force_recompile()
    vim.notify("Force recompiling plugins...", vim.log.levels.INFO)
    if M.compile() then
        vim.notify("Plugins recompiled successfully", vim.log.levels.INFO)
        return true
    else
        vim.notify("Failed to recompile plugins", vim.log.levels.ERROR)
        return false
    end
end

return M
